from pathlib import Path


def replace_once(path, old, new):
    text = path.read_text(encoding='utf-8')
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected exactly one match, found {count}: {old[:120]!r}')
    path.write_text(text.replace(old, new), encoding='utf-8')


portrait = Path('docs/js/portrait-utils.js')
png = Path('docs/js/png-plane-avatar.js')
hand = Path('docs/js/procedural-hand-attachments.js')
feet = Path('docs/js/procedural-leg-animation.js')
natural = Path('docs/js/natural-surface-materials.js')

# The body sprite PNG pipeline is the source of truth. It owns tinting AND the
# final CanvasTexture / unlit material conventions; the avatar plane is merely
# one consumer of this same sprite-PNG appearance path.
old = """// Explicit exports for classic-script consumers that render Three.js textures.\nwindow.bodySpriteTintForColor = bodySpriteTintForColor;\nwindow.getBodyTintedCanvas = getBodyTintedCanvas;\n"""
new = """// Canonical authored-PNG appearance path. Character body sprites, the final\n// avatar plane, and same-style 3D surface PNGs all go through this one API:\n// source PNG -> body-style recolor canvas -> CanvasTexture -> MeshBasicMaterial.\nfunction configureSpritePngTexture(THREE, texture, debugName) {\n  if (!texture) return texture;\n  if (debugName) texture.name = debugName;\n  // Keep the exact color-management behavior used by the assembled character\n  // sprite texture. Do not give same-style surface PNGs a separate encoding path.\n  texture.colorSpace = THREE.SRGBColorSpace;\n  texture.needsUpdate = true;\n  return texture;\n}\n\nfunction makeSpritePngCanvasTexture(THREE, imageOrCanvas, debugName) {\n  return configureSpritePngTexture(THREE, new THREE.CanvasTexture(imageOrCanvas), debugName);\n}\n\nfunction spritePngAlphaTest() {\n  return window.SCRATCHBONES_CONFIG?.game?.assets?.pngPlaneAvatar?.alphaTest ?? 0.001;\n}\n\nfunction spritePngMaterialOptions(THREE, texture, debugName, overrides = {}) {\n  return Object.assign({\n    name: debugName,\n    map: texture || null,\n    transparent: true,\n    alphaTest: spritePngAlphaTest(),\n    side: THREE.FrontSide,\n    depthTest: true,\n    depthWrite: true,\n    opacity: 1,\n  }, overrides);\n}\n\nfunction makeSpritePngUnlitMaterial(THREE, texture, debugName, overrides = {}) {\n  return new THREE.MeshBasicMaterial(spritePngMaterialOptions(THREE, texture, debugName, overrides));\n}\n\nwindow.HobunjiSpritePngSurface = {\n  tintForBodyColor: bodySpriteTintForColor,\n  tintBodyCanvas: getBodyTintedCanvas,\n  configureTexture: configureSpritePngTexture,\n  makeCanvasTexture: makeSpritePngCanvasTexture,\n  materialOptions: spritePngMaterialOptions,\n  makeMaterial: makeSpritePngUnlitMaterial,\n  alphaTest: spritePngAlphaTest,\n};\n\n// Legacy direct exports remain for editors and older consumers.\nwindow.bodySpriteTintForColor = bodySpriteTintForColor;\nwindow.getBodyTintedCanvas = getBodyTintedCanvas;\n"""
replace_once(portrait, old, new)

# Make png-plane-avatar a consumer/compatibility alias rather than the owner of
# the parity API.
old = """  // Canonical unlit appearance path for the PNG-plane avatar and any 3D\n  // surface that must visually match it. Keep the texture color-management\n  // behavior EXACTLY the same as the plane's long-standing CanvasTexture path:\n  // assign colorSpace directly (no separate r128 encoding fallback), leave the\n  // CanvasTexture's filter/mipmap defaults alone, and use MeshBasicMaterial.\n  function configurePngPlaneUnlitTexture(THREE, texture, debugName) {\n    if (!texture) return texture;\n    if (debugName) texture.name = debugName;\n    texture.colorSpace = THREE.SRGBColorSpace;\n    texture.needsUpdate = true;\n    return texture;\n  }\n\n  function pngPlaneUnlitMaterialOptions(THREE, texture, debugName, overrides = {}) {\n    return Object.assign({\n      name: debugName,\n      map: texture || null,\n      transparent: true,\n      alphaTest: cfg().alphaTest ?? 0.001,\n      side: THREE.FrontSide,\n      depthTest: true,\n      // alphaTest already discards fully-transparent texels, so the opaque\n      // sprite silhouette can safely write depth — without this, the depth\n      // buffer behind the sprite still holds whatever was rendered before it\n      // (e.g. a building wall), so later passes that re-test depth (like the\n      // shell outline pass) draw straight through the sprite as if it weren't\n      // there.\n      depthWrite: true,\n      opacity: 1,\n    }, overrides);\n  }\n\n  function makePngPlaneUnlitMaterial(THREE, texture, debugName, overrides = {}) {\n    return new THREE.MeshBasicMaterial(pngPlaneUnlitMaterialOptions(THREE, texture, debugName, overrides));\n  }\n\n  function makeTextureFromCanvas(THREE, canvasEl, debugName) {\n    return configurePngPlaneUnlitTexture(THREE, new THREE.CanvasTexture(canvasEl), debugName);\n  }\n\n  function makeSpriteMaterial(THREE, texture, debugName) {\n    return makePngPlaneUnlitMaterial(THREE, texture, debugName);\n  }\n\n  // Classic-script consumers (procedural hands/feet and natural surfaces) use\n  // this exact builder instead of maintaining their own interpretation of\n  // \"unlit like the portrait plane\".\n  window.HobunjiPngPlaneUnlit = {\n    configureTexture: configurePngPlaneUnlitTexture,\n    materialOptions: pngPlaneUnlitMaterialOptions,\n    makeMaterial: makePngPlaneUnlitMaterial,\n    alphaTest: () => cfg().alphaTest ?? 0.001,\n  };\n"""
new = """  // The plane is only a carrier for the authored character PNG composite.\n  // The actual source of truth lives with the sprite PNG/tint pipeline in\n  // portrait-utils.js so same-style PNGs used on 3D surfaces share it too.\n  const spritePngSurface = window.HobunjiSpritePngSurface;\n\n  function makeTextureFromCanvas(THREE, canvasEl, debugName) {\n    if (spritePngSurface?.makeCanvasTexture) {\n      return spritePngSurface.makeCanvasTexture(THREE, canvasEl, debugName);\n    }\n    const texture = new THREE.CanvasTexture(canvasEl);\n    texture.name = debugName;\n    texture.colorSpace = THREE.SRGBColorSpace;\n    texture.needsUpdate = true;\n    return texture;\n  }\n\n  function makeSpriteMaterial(THREE, texture, debugName) {\n    if (spritePngSurface?.makeMaterial) {\n      return spritePngSurface.makeMaterial(THREE, texture, debugName);\n    }\n    return new THREE.MeshBasicMaterial({\n      name: debugName, map: texture, transparent: true,\n      alphaTest: cfg().alphaTest ?? 0.001, side: THREE.FrontSide,\n      depthTest: true, depthWrite: true, opacity: 1,\n    });\n  }\n\n  // Compatibility alias for older callers; this is now literally the sprite\n  // PNG surface API rather than an independently maintained plane-only copy.\n  window.HobunjiPngPlaneUnlit = spritePngSurface || window.HobunjiPngPlaneUnlit;\n"""
replace_once(png, old, new)

# Hands: source PNG recoloring must enter through the same sprite-PNG API.
old = """      if (typeof global.getBodyTintedCanvas === 'function') {\n        // This is the same function renderProfile uses for body sprite layers.\n        source = global.getBodyTintedCanvas(image, 'assets/textures/wavy_surface.png', descriptor, speciesId, 'A') || image;\n      } else {\n"""
new = """      const spritePng = global.HobunjiSpritePngSurface;\n      if (typeof spritePng?.tintBodyCanvas === 'function' || typeof global.getBodyTintedCanvas === 'function') {\n        // Same authored-PNG recolor entry point used by the character body art.\n        const tintBodyCanvas = spritePng?.tintBodyCanvas || global.getBodyTintedCanvas;\n        source = tintBodyCanvas(image, 'assets/textures/wavy_surface.png', descriptor, speciesId, 'A') || image;\n      } else {\n"""
replace_once(hand, old, new)

# Feet: same exact body-PNG tint entry point; body role passes real species id.
old = """      if (typeof window.getBodyTintedCanvas === 'function') {\n        // Same descriptor -> species tint-mode -> _imageForTint path used by\n        // the portrait body sprite itself. Fixed bone/keratin hex descriptors\n        // pass an empty species id so they retain the default shade-fill mode.\n        source = window.getBodyTintedCanvas(img, sourcePath, colorDescriptor, tintSpeciesId, 'A') || null;\n      } else if (typeof window.shadeFillTintForBodyColor === 'function' && typeof window.getShadeFillCanvas === 'function') {\n"""
new = """      const tintBodyCanvas = window.HobunjiSpritePngSurface?.tintBodyCanvas || window.getBodyTintedCanvas;\n      if (typeof tintBodyCanvas === 'function') {\n        // Same descriptor -> species tint-mode -> _imageForTint path used by\n        // the portrait body sprite itself. Fixed bone/keratin hex descriptors\n        // pass an empty species id so they retain the default shade-fill mode.\n        source = tintBodyCanvas(img, sourcePath, colorDescriptor, tintSpeciesId, 'A') || null;\n      } else if (typeof window.shadeFillTintForBodyColor === 'function' && typeof window.getShadeFillCanvas === 'function') {\n"""
replace_once(feet, old, new)

# Natural rock/cliff PNGs: same authored-PNG tint entry point with fixed #808080.
old = """      if (typeof window.getBodyTintedCanvas !== 'function') {\n        console.warn('[natural-surface] portrait body tint helper unavailable; keeping flat tint', path, tint);\n        return;\n      }\n      // Empty species id intentionally follows bodyTintModeForSpecies(''), whose\n      // default is the same shadeFill mode used by ordinary body sprites. A hex\n      // descriptor is already absolute, so no species swatch conversion occurs.\n      const canvas = window.getBodyTintedCanvas(image, cacheKey, { hex: tint }, '', 'A');\n"""
new = """      const tintBodyCanvas = window.HobunjiSpritePngSurface?.tintBodyCanvas || window.getBodyTintedCanvas;\n      if (typeof tintBodyCanvas !== 'function') {\n        console.warn('[natural-surface] portrait body PNG tint helper unavailable; keeping flat tint', path, tint);\n        return;\n      }\n      // Empty species id intentionally follows bodyTintModeForSpecies(''), whose\n      // default is the same shadeFill mode used by ordinary body sprites. A hex\n      // descriptor is already absolute, so no species swatch conversion occurs.\n      const canvas = tintBodyCanvas(image, cacheKey, { hex: tint }, '', 'A');\n"""
replace_once(natural, old, new)

# Ensure all texture/material consumers now resolve to the sprite-PNG API first.
for path in (hand, feet, natural):
    text = path.read_text(encoding='utf-8')
    text = text.replace('global.HobunjiPngPlaneUnlit?.', '(global.HobunjiSpritePngSurface || global.HobunjiPngPlaneUnlit)?.')
    text = text.replace('window.HobunjiPngPlaneUnlit?.', '(window.HobunjiSpritePngSurface || window.HobunjiPngPlaneUnlit)?.')
    path.write_text(text, encoding='utf-8')
