from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing patch target: {label}')
    return text.replace(old, new, 1)

path = Path('docs/tools/locale-editor/terrain-placement.js')
s = path.read_text(encoding='utf-8')

s = replace_once(s,
"""  const brush = {\n    terrain: 'plateauCliff',\n    strength: 'required',\n    weight: 1,\n    facing: 'any',\n    height: { mode: 'any', min: null, max: null },\n    carveToLocaleFloor: true,\n  }; // Shared brush state; embedded mode ignores strength/weight while probe mode ignores carveToLocaleFloor.\n\n  function clone(value) { return JSON.parse(JSON.stringify(value)); }\n""",
"""  const brush = {\n    terrain: 'plateauCliff',\n    strength: 'required',\n    weight: 1,\n    facing: 'any',\n    height: { mode: 'any', min: null, max: null },\n    carveToLocaleFloor: true,\n  }; // Shared brush state; embedded mode ignores strength/weight while probe mode ignores carveToLocaleFloor.\n\n  // One specific pre-sync Locale Editor build could leave Banubu with a large\n  // south-facing cliff rectangle in browser-local workspace data. Keep local\n  // authoring authoritative in general, but migrate that known malformed\n  // signature back to the canonical cliff-base rule set once.\n  const BANUBU_CANONICAL_RULES = {\n    terrainAnchors: {\n      '3,2': { terrain: 'plateauCliff', strength: 'preferred', weight: 2, facing: 'north', height: { mode: 'relativeRange', min: 0, max: 0 } },\n      '4,2': { terrain: 'plateauCliff', strength: 'required', weight: 1, facing: 'north', height: { mode: 'relativeRange', min: 0, max: 0 } },\n      '5,2': { terrain: 'plateauCliff', strength: 'preferred', weight: 2, facing: 'north', height: { mode: 'relativeRange', min: 0, max: 0 } },\n      '3,3': { terrain: 'plateauCliff', strength: 'preferred', weight: 2, facing: 'north', height: { mode: 'relativeRange', min: 1, max: null } },\n      '4,3': { terrain: 'plateauCliff', strength: 'required', weight: 1, facing: 'north', height: { mode: 'relativeRange', min: 1, max: null } },\n      '5,3': { terrain: 'plateauCliff', strength: 'preferred', weight: 2, facing: 'north', height: { mode: 'relativeRange', min: 1, max: null } },\n    },\n    embeddedTiles: {\n      '3,3': { terrain: 'plateau', facing: 'any', height: { mode: 'relativeRange', min: 1, max: null }, carveToLocaleFloor: true },\n      '4,3': { terrain: 'plateau', facing: 'any', height: { mode: 'relativeRange', min: 1, max: null }, carveToLocaleFloor: true },\n      '5,3': { terrain: 'plateau', facing: 'any', height: { mode: 'relativeRange', min: 1, max: null }, carveToLocaleFloor: true },\n    },\n  };\n\n  function clone(value) { return JSON.parse(JSON.stringify(value)); }\n\n  function isKnownBrokenBanubuRules(locale, rules) {\n    if (locale?.id !== 'locale_banubu_shrine' || locale?.placement?.floorMode !== 'nextLowerCliffTier') return false;\n    const anchors = Object.values(rules?.terrainAnchors || {});\n    if (anchors.length < 20 || Object.keys(rules?.embeddedTiles || {}).length !== 0) return false;\n    return anchors.every(rule => rule?.terrain === 'plateauCliff' &&\n      rule?.strength === 'required' && rule?.facing === 'south' &&\n      (rule?.height?.mode || 'any') === 'any');\n  }\n\n  function migrateKnownBrokenRules(locale, rules) {\n    if (!isKnownBrokenBanubuRules(locale, rules)) return rules;\n    return clone(BANUBU_CANONICAL_RULES);\n  }\n""", 'Banubu migration helpers')

s = replace_once(s,
"""  function reconcileRulesFromLocale(locale) {\n    if (!locale?.id) return { terrainAnchors: {}, embeddedTiles: {} };\n    const fromLocale = rulesFromLocale(locale);\n    // Explicit workspace fields are authoritative. This replaces obsolete\n    // sidecar data instead of resurrecting it after a newer locale is loaded.\n    if (hasPersistedRuleFields(locale)) {\n      if (!sameRules(store.byLocale[locale.id], fromLocale)) {\n        store.byLocale[locale.id] = fromLocale;\n        saveRuleStore();\n      }\n    } else if (!store.byLocale[locale.id]) {\n      store.byLocale[locale.id] = fromLocale;\n      saveRuleStore();\n    }\n    const rules = ensureRules(locale);\n    syncRulesToMainLocale(locale.id, rules);\n    return rules;\n  }\n""",
"""  function reconcileRulesFromLocale(locale) {\n    if (!locale?.id) return { terrainAnchors: {}, embeddedTiles: {} };\n    let fromLocale = rulesFromLocale(locale);\n    const migrated = migrateKnownBrokenRules(locale, fromLocale);\n    if (migrated !== fromLocale) {\n      fromLocale = migrated;\n      store.byLocale[locale.id] = fromLocale;\n      syncRulesToMainLocale(locale.id, fromLocale);\n      saveRuleStore();\n      debug('repaired legacy Banubu south-cliff terrain rules to canonical north-facing cliff-base rules');\n      return fromLocale;\n    }\n    // Explicit workspace fields are authoritative. This replaces obsolete\n    // sidecar data instead of resurrecting it after a newer locale is loaded.\n    if (hasPersistedRuleFields(locale)) {\n      if (!sameRules(store.byLocale[locale.id], fromLocale)) {\n        store.byLocale[locale.id] = fromLocale;\n        saveRuleStore();\n      }\n    } else if (!store.byLocale[locale.id]) {\n      store.byLocale[locale.id] = fromLocale;\n      saveRuleStore();\n    }\n    const rules = ensureRules(locale);\n    syncRulesToMainLocale(locale.id, rules);\n    return rules;\n  }\n""", 'reconcile migration')

path.write_text(s, encoding='utf-8')

path = Path('scripts/test-banubu-wilderness-lab-generation.js')
s = path.read_text(encoding='utf-8')

s = replace_once(s,
"""const locale = require('../docs/config/locales/locale_banubu_shrine.json');\n\nterrainPlacement.install(generator);\n""",
"""const locale = require('../docs/config/locales/locale_banubu_shrine.json');\nconst fs = require('fs');\nconst path = require('path');\n\nterrainPlacement.install(generator);\n\nconst terrainEditorSource = fs.readFileSync(path.resolve(__dirname, '../docs/tools/locale-editor/terrain-placement.js'), 'utf8');\nassert(terrainEditorSource.includes('isKnownBrokenBanubuRules'), 'Locale Editor must recognize the known stale Banubu south-cliff browser-workspace signature');\nassert(terrainEditorSource.includes('BANUBU_CANONICAL_RULES'), 'Locale Editor must carry the canonical Banubu repair rule set');\nassert(terrainEditorSource.includes("anchors.length < 20") && terrainEditorSource.includes("rule?.facing === 'south'"), 'Banubu migration must stay narrowly scoped to the obsolete large south-facing rule grid');\n""", 'migration regression setup')

s = replace_once(s,
"""  'locale-preview|locale_banubu_shrine|map_northern_cliffs|mtzztqpk|s0ho2n6',\n];\n""",
"""  'locale-preview|locale_banubu_shrine|map_northern_cliffs|mtzztqpk|s0ho2n6',\n  'locale-preview|locale_banubu_shrine|map_northern_cliffs|mu0bd5bo|khx6y2e',\n];\n""", 'new debug seed regression')

path.write_text(s, encoding='utf-8')
