from pathlib import Path


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'{label}: expected exactly 1 occurrence, found {count}')
    return text.replace(old, new, 1)


generator_path = Path('docs/js/npc-crafting-commission-generator.js')
generator = generator_path.read_text(encoding='utf-8')
generator = replace_once(
    generator,
    "    const catalog = (craftingDeps?.FURNITURE_BLUEPRINT_CATALOG || []).filter(entry => entry?.key && entry?.furnitureKey && entry?.name && entry?.craftCost); // Only real reusable-blueprint furniture can be requested.\n",
    "    const catalog = (craftingDeps?.FURNITURE_BLUEPRINT_CATALOG || []).filter(entry => entry?.key && entry?.furnitureKey && entry?.name && entry?.craftCost && !entry?.moteOnly && !entry?.masteryUnlockId); // Only ordinary reusable blueprints can be granted free; Crafting Mastery/Mote unlocks such as Advanced Loom must keep their progression gate.\n",
    'commission Mote-only exclusion',
)
generator_path.write_text(generator, encoding='utf-8')

# Extend the permanent regression generated by the main finalizer.
test_path = Path('scripts/test-advanced-loom-cooking-yield.js')
test = test_path.read_text(encoding='utf-8')
test = replace_once(
    test,
    "const carpenter = fs.readFileSync('docs/js/carpenter-shop.js', 'utf8');\n",
    "const carpenter = fs.readFileSync('docs/js/carpenter-shop.js', 'utf8');\nconst commissions = fs.readFileSync('docs/js/npc-crafting-commission-generator.js', 'utf8');\n",
    'commission regression source',
)
test = replace_once(
    test,
    "assert.match(carpenter, /!bp\\.moteOnly/, 'Mote-only Advanced Loom blueprint is excluded from the gold carpenter shop');\n",
    "assert.match(carpenter, /!bp\\.moteOnly/, 'Mote-only Advanced Loom blueprint is excluded from the gold carpenter shop');\nassert.match(commissions, /!entry\\?\\.moteOnly && !entry\\?\\.masteryUnlockId/, 'Mote/Crafting-Mastery blueprints cannot be granted free by furniture commissions');\n",
    'commission regression assertion',
)
test_path.write_text(test, encoding='utf-8')

# One-shot branch helper; keep the finished branch free of patch machinery.
Path('scripts/tmp-loom-finalizer-extra.py').unlink(missing_ok=True)
